openapi: 3.0.0
info:
  title: Open Food API
  description: This is the API documentation for the Open Food application.
  version: 1.0.0

paths:
  /:
    get:
      summary: Get API information
      responses:
        '200':
          description: Successful operation
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: Successful operation
  /products/{id}:
    get:
      summary: Get a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
        '404':
          description: Product not found
  /sync:
    get:
      summary: Manually trigger synchronization
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    Product:
      type: object
      properties:
        code:
          type: String
        barcode:
          type: String
        url:
          type: String
        product_name:
          type: String
        quantity:
          type: String
        categories:
          type: String
        packaging:
          type: String
        brands:
          type: String
        image_url:
          type: String
        status:
          type: String
        imported_t:
          type: DateTime
