openapi: 3.0.0
info:
  title: Open Food API
  description: This is the API documentation for the Open Food application.
  version: 1.0.0

paths:
  /products:
    get:
      summary: Retrieve a list of products
      description: Returns a paginated list of products.
      parameters:
        - name: page
          in: query
          description: The page number for pagination.
          schema:
            type: integer
            minimum: 1
          required: false
          example: 1
        - name: per_page
          in: query
          description: The number of products per page.
          schema:
            type: integer
            minimum: 1
            maximum: 50
          required: false
          example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request

  /products/{code}:
    get:
      summary: Retrieve a product by code
      description: Returns a product based on its unique code.
      parameters:
        - name: code
          in: path
          description: The code of the product.
          schema:
            type: string
          required: true
          example: ABC123
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Not Found

components:
  schemas:
    Product:
      type: object
      properties:
        code:
          type: string
          description: The code of the product.
        name:
          type: string
          description: The name of the product.
        quantity:
          type: string
          description: The quantity of the product.
        price:
          type: number
          description: The price of the product.
